const { readFileSync, writeFileSync } = require("node:fs");
const path = require("node:path");

let enumString = "// This file is auto-generated by 'utils/generateEnum.js'."
	+ "\n// Do not edit it directly.";

// Countries
try {
	const countries = JSON.parse(readFileSync(path.join(__dirname, "countries.json"), "utf-8"));

	const enumLines = countries.map(
		(country) => `\t${country.code + '_' + country.name.replace(/[\s\-']/g, '_').replace(/[\(\)]/g, '$')} = ${country.id}`
	);
	const typeLines = countries.map(
		(country) => `\t| "${country.code}"`
	)

	enumString += `\n\nenum Countries {\n\tNone = 0,\n${enumLines.join(",\n")}\n}`;
	enumString += `\n\ntype CountriesCodes =\n${typeLines.join("\n")}`;
} catch (error) {}

writeFileSync(path.join(__dirname, "..", "src", "enum.ts"), enumString + '\n');
