// This file is auto-generated by 'utils/generateEnum.js'.
// Do not edit it directly.

enum Countries {
	None = 0,
	AF_Afghanistan = 1,
	AL_Albania = 2,
	DZ_Algeria = 3,
	AS_American_Samoa = 4,
	AD_Andorra = 5,
	AO_Angola = 6,
	AI_Anguilla = 7,
	AQ_Antarctica = 8,
	AG_Antigua_and_Barbuda = 9,
	AR_Argentina = 10,
	AM_Armenia = 11,
	AW_Aruba = 12,
	AU_Australia = 13,
	AT_Austria = 14,
	AZ_Azerbaijan = 15,
	BS_Bahamas = 16,
	BH_Bahrain = 17,
	BD_Bangladesh = 18,
	BB_Barbados = 19,
	BY_Belarus = 20,
	BE_Belgium = 21,
	BZ_Belize = 22,
	BJ_Benin = 23,
	BM_Bermuda = 24,
	BT_Bhutan = 25,
	BO_Bolivia = 26,
	BQ_Bonaire = 27,
	BA_Bosnia_and_Herzegovina = 28,
	BW_Botswana = 29,
	BV_Bouvet_Island = 30,
	BR_Brazil = 31,
	IO_British_Indian_Ocean_Territory = 32,
	BN_Brunei_Darussalam = 33,
	BG_Bulgaria = 34,
	BF_Burkina_Faso = 35,
	BI_Burundi = 36,
	CV_Cabo_Verde = 37,
	KH_Cambodia = 38,
	CM_Cameroon = 39,
	CA_Canada = 40,
	KY_Cayman_Islands = 41,
	CF_Central_African_Republic = 42,
	TD_Chad = 43,
	CL_Chile = 44,
	CN_China = 45,
	CX_Christmas_Island = 46,
	CC_Cocos_$Keeling$_Islands = 47,
	CO_Colombia = 48,
	KM_Comoros = 49,
	CG_Congo = 50,
	CK_Cook_Islands = 51,
	CR_Costa_Rica = 52,
	HR_Croatia = 53,
	CU_Cuba = 54,
	CW_Curaçao = 55,
	CY_Cyprus = 56,
	CZ_Czechia = 57,
	CI_Côte_d_Ivoire = 58,
	DK_Denmark = 59,
	DJ_Djibouti = 60,
	DM_Dominica = 61,
	DO_Dominican_Republic = 62,
	EC_Ecuador = 63,
	EG_Egypt = 64,
	SV_El_Salvador = 65,
	GQ_Equatorial_Guinea = 66,
	ER_Eritrea = 67,
	EE_Estonia = 68,
	SZ_Eswatini = 69,
	ET_Ethiopia = 70,
	FK_Falkland_Islands_$Malvinas$ = 71,
	FO_Faroe_Islands = 72,
	FJ_Fiji = 73,
	FI_Finland = 74,
	FR_France = 75,
	GF_French_Guiana = 76,
	PF_French_Polynesia = 77,
	TF_French_Southern_Territories = 78,
	GA_Gabon = 79,
	GM_Gambia = 80,
	GE_Georgia = 81,
	DE_Germany = 82,
	GH_Ghana = 83,
	GI_Gibraltar = 84,
	GR_Greece = 85,
	GL_Greenland = 86,
	GD_Grenada = 87,
	GP_Guadeloupe = 88,
	GU_Guam = 89,
	GT_Guatemala = 90,
	GG_Guernsey = 91,
	GN_Guinea = 92,
	GW_Guinea_Bissau = 93,
	GY_Guyana = 94,
	HT_Haiti = 95,
	HM_Heard_Island_and_McDonald_Islands = 96,
	HN_Honduras = 97,
	HK_Hong_Kong = 98,
	HU_Hungary = 99,
	IS_Iceland = 100,
	IN_India = 101,
	ID_Indonesia = 102,
	IR_Iran = 103,
	IQ_Iraq = 104,
	IE_Ireland = 105,
	IM_Isle_of_Man = 106,
	IL_Israel = 107,
	IT_Italy = 108,
	JM_Jamaica = 109,
	JP_Japan = 110,
	JE_Jersey = 111,
	JO_Jordan = 112,
	KZ_Kazakhstan = 113,
	KE_Kenya = 114,
	KI_Kiribati = 115,
	XK_Kosovo = 116,
	KW_Kuwait = 117,
	KG_Kyrgyzstan = 118,
	LA_Laos = 119,
	LV_Latvia = 120,
	LB_Lebanon = 121,
	LS_Lesotho = 122,
	LR_Liberia = 123,
	LY_Libya = 124,
	LI_Liechtenstein = 125,
	LT_Lithuania = 126,
	LU_Luxembourg = 127,
	MO_Macao = 128,
	MG_Madagascar = 129,
	MW_Malawi = 130,
	MY_Malaysia = 131,
	MV_Maldives = 132,
	ML_Mali = 133,
	MT_Malta = 134,
	MH_Marshall_Islands = 135,
	MQ_Martinique = 136,
	MR_Mauritania = 137,
	MU_Mauritius = 138,
	YT_Mayotte = 139,
	MX_Mexico = 140,
	FM_Micronesia = 141,
	MD_Moldova = 142,
	MC_Monaco = 143,
	MN_Mongolia = 144,
	ME_Montenegro = 145,
	MS_Montserrat = 146,
	MA_Morocco = 147,
	MZ_Mozambique = 148,
	MM_Myanmar = 149,
	NA_Namibia = 150,
	NR_Nauru = 151,
	NP_Nepal = 152,
	NL_Netherlands = 153,
	NC_New_Caledonia = 154,
	NZ_New_Zealand = 155,
	NI_Nicaragua = 156,
	NE_Niger = 157,
	NG_Nigeria = 158,
	NU_Niue = 159,
	NF_Norfolk_Island = 160,
	KP_North_Korea = 161,
	MK_North_Macedonia = 162,
	MP_Northern_Mariana_Islands = 163,
	NO_Norway = 164,
	OM_Oman = 165,
	PK_Pakistan = 166,
	PW_Palau = 167,
	PS_Palestine = 168,
	PA_Panama = 169,
	PG_Papua_New_Guinea = 170,
	PY_Paraguay = 171,
	PE_Peru = 172,
	PH_Philippines = 173,
	PN_Pitcairn = 174,
	PL_Poland = 175,
	PT_Portugal = 176,
	PR_Puerto_Rico = 177,
	QA_Qatar = 178,
	CD_Republic_of_the_Congo = 179,
	RO_Romania = 180,
	RU_Russia = 181,
	RW_Rwanda = 182,
	RE_Réunion = 183,
	BL_Saint_Barthélemy = 184,
	SH_Saint_Helena = 185,
	KN_Saint_Kitts_and_Nevis = 186,
	LC_Saint_Lucia = 187,
	MF_Saint_Martin_$French_part$ = 188,
	PM_Saint_Pierre_and_Miquelon = 189,
	VC_Saint_Vincent_and_the_Grenadines = 190,
	WS_Samoa = 191,
	SM_San_Marino = 192,
	ST_Sao_Tome_and_Principe = 193,
	SA_Saudi_Arabia = 194,
	SN_Senegal = 195,
	RS_Serbia = 196,
	SC_Seychelles = 197,
	SL_Sierra_Leone = 198,
	SG_Singapore = 199,
	SX_Sint_Maarten_$Dutch_part$ = 200,
	SK_Slovakia = 201,
	SI_Slovenia = 202,
	SB_Solomon_Islands = 203,
	SO_Somalia = 204,
	ZA_South_Africa = 205,
	GS_South_Georgia_and_the_South_Sandwich_Islands = 206,
	KR_South_Korea = 207,
	SS_South_Sudan = 208,
	ES_Spain = 209,
	LK_Sri_Lanka = 210,
	SD_Sudan = 211,
	SR_Suriname = 212,
	SJ_Svalbard_and_Jan_Mayen = 213,
	SE_Sweden = 214,
	CH_Switzerland = 215,
	SY_Syrian_Arab_Republic = 216,
	TW_Taiwan = 217,
	TJ_Tajikistan = 218,
	TZ_Tanzania = 219,
	TH_Thailand = 220,
	TL_Timor_Leste = 221,
	TG_Togo = 222,
	TK_Tokelau = 223,
	TO_Tonga = 224,
	TT_Trinidad_and_Tobago = 225,
	TN_Tunisia = 226,
	TM_Turkmenistan = 227,
	TC_Turks_and_Caicos_Islands = 228,
	TV_Tuvalu = 229,
	TR_Türkiye = 230,
	UG_Uganda = 231,
	UA_Ukraine = 232,
	AE_United_Arab_Emirates = 233,
	GB_United_Kingdom = 234,
	US_United_States = 235,
	UM_United_States_Minor_Outlying_Islands = 236,
	UY_Uruguay = 237,
	UZ_Uzbekistan = 238,
	VU_Vanuatu = 239,
	VA_Vatican_City = 240,
	VE_Venezuela = 241,
	VN_Viet_Nam = 242,
	VG_Virgin_Islands = 243,
	VI_Virgin_Islands = 244,
	WF_Wallis_and_Futuna = 245,
	EH_Western_Sahara = 246,
	YE_Yemen = 247,
	ZM_Zambia = 248,
	ZW_Zimbabwe = 249,
	AX_Åland_Islands = 250,
	IC_Canary_Islands = 251
}

type CountriesCodes =
	| "AF"
	| "AL"
	| "DZ"
	| "AS"
	| "AD"
	| "AO"
	| "AI"
	| "AQ"
	| "AG"
	| "AR"
	| "AM"
	| "AW"
	| "AU"
	| "AT"
	| "AZ"
	| "BS"
	| "BH"
	| "BD"
	| "BB"
	| "BY"
	| "BE"
	| "BZ"
	| "BJ"
	| "BM"
	| "BT"
	| "BO"
	| "BQ"
	| "BA"
	| "BW"
	| "BV"
	| "BR"
	| "IO"
	| "BN"
	| "BG"
	| "BF"
	| "BI"
	| "CV"
	| "KH"
	| "CM"
	| "CA"
	| "KY"
	| "CF"
	| "TD"
	| "CL"
	| "CN"
	| "CX"
	| "CC"
	| "CO"
	| "KM"
	| "CG"
	| "CK"
	| "CR"
	| "HR"
	| "CU"
	| "CW"
	| "CY"
	| "CZ"
	| "CI"
	| "DK"
	| "DJ"
	| "DM"
	| "DO"
	| "EC"
	| "EG"
	| "SV"
	| "GQ"
	| "ER"
	| "EE"
	| "SZ"
	| "ET"
	| "FK"
	| "FO"
	| "FJ"
	| "FI"
	| "FR"
	| "GF"
	| "PF"
	| "TF"
	| "GA"
	| "GM"
	| "GE"
	| "DE"
	| "GH"
	| "GI"
	| "GR"
	| "GL"
	| "GD"
	| "GP"
	| "GU"
	| "GT"
	| "GG"
	| "GN"
	| "GW"
	| "GY"
	| "HT"
	| "HM"
	| "HN"
	| "HK"
	| "HU"
	| "IS"
	| "IN"
	| "ID"
	| "IR"
	| "IQ"
	| "IE"
	| "IM"
	| "IL"
	| "IT"
	| "JM"
	| "JP"
	| "JE"
	| "JO"
	| "KZ"
	| "KE"
	| "KI"
	| "XK"
	| "KW"
	| "KG"
	| "LA"
	| "LV"
	| "LB"
	| "LS"
	| "LR"
	| "LY"
	| "LI"
	| "LT"
	| "LU"
	| "MO"
	| "MG"
	| "MW"
	| "MY"
	| "MV"
	| "ML"
	| "MT"
	| "MH"
	| "MQ"
	| "MR"
	| "MU"
	| "YT"
	| "MX"
	| "FM"
	| "MD"
	| "MC"
	| "MN"
	| "ME"
	| "MS"
	| "MA"
	| "MZ"
	| "MM"
	| "NA"
	| "NR"
	| "NP"
	| "NL"
	| "NC"
	| "NZ"
	| "NI"
	| "NE"
	| "NG"
	| "NU"
	| "NF"
	| "KP"
	| "MK"
	| "MP"
	| "NO"
	| "OM"
	| "PK"
	| "PW"
	| "PS"
	| "PA"
	| "PG"
	| "PY"
	| "PE"
	| "PH"
	| "PN"
	| "PL"
	| "PT"
	| "PR"
	| "QA"
	| "CD"
	| "RO"
	| "RU"
	| "RW"
	| "RE"
	| "BL"
	| "SH"
	| "KN"
	| "LC"
	| "MF"
	| "PM"
	| "VC"
	| "WS"
	| "SM"
	| "ST"
	| "SA"
	| "SN"
	| "RS"
	| "SC"
	| "SL"
	| "SG"
	| "SX"
	| "SK"
	| "SI"
	| "SB"
	| "SO"
	| "ZA"
	| "GS"
	| "KR"
	| "SS"
	| "ES"
	| "LK"
	| "SD"
	| "SR"
	| "SJ"
	| "SE"
	| "CH"
	| "SY"
	| "TW"
	| "TJ"
	| "TZ"
	| "TH"
	| "TL"
	| "TG"
	| "TK"
	| "TO"
	| "TT"
	| "TN"
	| "TM"
	| "TC"
	| "TV"
	| "TR"
	| "UG"
	| "UA"
	| "AE"
	| "GB"
	| "US"
	| "UM"
	| "UY"
	| "UZ"
	| "VU"
	| "VA"
	| "VE"
	| "VN"
	| "VG"
	| "VI"
	| "WF"
	| "EH"
	| "YE"
	| "ZM"
	| "ZW"
	| "AX"
	| "IC"
